name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
        default: '1.0.0'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create tag if it does not exist
        shell: bash
        run: |
          if git rev-parse "refs/tags/${{ github.event.inputs.tag }}" >/dev/null 2>&1; then
            echo "Tag '${{ github.event.inputs.tag }}' already exists."
          else
            echo "Creating tag '${{ github.event.inputs.tag }}'"
            git tag ${{ github.event.inputs.tag }}
            git push origin ${{ github.event.inputs.tag }}
          fi
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            build-platform: linux/amd64
          - os: macos-latest
            build-platform: darwin/universal
          - os: windows-latest
            build-platform: windows/amd64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Wails Application
        uses: dAppServer/wails-build-action@main
        with:
          build-name: synterix
          build-platform: ${{ matrix.build-platform }}
          package: true

      - name: Zip build artifacts
        run: |
          mkdir -p dist
          zip -r dist/synterix-${{ matrix.build-platform // '/' / '-' }}.zip build/bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: synterix-${{ matrix.os }}-${{ github.event.inputs.version }}
          path: ./build/bin/*

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: dist/synterix-${{ matrix.build-platform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
