name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
        default: '1.0.0'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            build-platform: linux/amd64
          - os: macos-latest
            build-platform: darwin/universal
          - os: windows-latest
            build-platform: windows/amd64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Wails Application
        uses: dAppServer/wails-build-action@main
        with:
          build-name: synterix
          build-platform: ${{ matrix.build-platform }}
          package: true