name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            build-platform: linux/amd64
          - os: macos-latest
            build-platform: darwin/universal
          - os: windows-latest
            build-platform: windows/amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Wails Application
        uses: dAppServer/wails-build-action@main
        with:
          build-name: synterix
          build-platform: ${{ matrix.build-platform }}
          package: true

      - name: Create Git Tag
        run: |
          TAG="v${{ github.event.inputs.version }}"
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag already exists, skipping creation."
          else
            git config user.name "${{ github.actor }}"
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git tag -a "$TAG" -m "Release $TAG"
            git push origin "$TAG"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: "v${{ github.event.inputs.version }}"
          body: "Release version ${{ github.event.inputs.version }} - Built for all platforms"
          draft: false
          prerelease: false
          files: |
            ./build/bin/*

